name: covered
description: Test coverage for both server-side and web-based dart projects.
version: 0.0.1
homepage: https://www.github.com/komposten/
repository: https://www.github.com/komposten/covered
issue_tracker: https://www.github.com/komposten/covered/issues
author: Jakob Hjelm <komposten585@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
