name: covered
description: Code coverage for Dart applications running in the Dart VM and browsers.
version: 0.1.1
homepage: https://www.github.com/komposten/
repository: https://www.github.com/komposten/covered
issue_tracker: https://www.github.com/komposten/covered/issues
author: Jakob Hjelm <komposten585@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  resource: ^2.1.6
  args: ^1.5.2
  test: ^1.6.0
  boolean_selector: ^1.0.5
  path: ^1.6.4
  coverage: ^0.13.2
  collection: ^1.14.12
  source_maps: ^0.10.8
  lcov: ^5.2.0

dev_dependencies:
  pedantic: ^1.7.0
