name: Dart CI

on:
  push:
    branches:
    - master
    - develop
    - release-*

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dart_version: [2.2.0, latest]
        platform: [vm, firefox]
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Dart SDK
      run: cd .github/scripts && chmod +x install_dart.sh && sudo ./install_dart.sh ${{ matrix.dart_version }}
    - name: Install dependencies
      run:  /usr/lib/dart/bin/pub get
    - name: Run tests
      run:  xvfb-run -a /usr/lib/dart/bin/pub run test -p ${{ matrix.platform }}
      
  analyse:
    name: Code analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dart_version: [2.2.0, latest]
    
    container:
      image:  google/dart:${{ matrix.dart_version }}
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: pub get
    - name: Run analyser
      run: dartanalyzer lib test example

  format:
    name: Code format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dart_version: [2.2.0, latest]
    
    container:
      image:  google/dart:${{ matrix.dart_version }}
    
    steps:
    - uses: actions/checkout@v1
    - name: Checking format
      run: dartfmt -n .
